### ISSUE TITLE
accessExp bug

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-cms-koa-core#1]
https://github.com/TaleLin/lin-cms-koa-core/blob/351f4a1d7e99b0773306561f6eeecc675932e8fd/lib/jwt.ts#L108

这儿要用工厂模式，否则accessExp 是服务启动时生成值，以后固定不变。 改为(js)：
```
const jwt = ()=> {   
  return new Token(   
  config.getItem("secret"),   
  config.getItem("accessExp"),   
  config.getItem("refreshExp")   
) 
}
```
引用jwt改：
`  jwt().createAccessToken(user.id)`

如果改accessExp=60 * 60; // 1h; 虽可行，但Token类的意义偏离了，应每个token的实例不同，才能准确表达token对象定义。

**Comment by PedroGao** [comment]
好，这个我们会讨论一下的，谢谢反馈

**Comment by PedroGao** [comment]
昨天，我们讨论了一下。我们还是觉得token的实例可以是唯一的，每个用户对应的是不同的令牌。
