### ISSUE TITLE
User 定义bug

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-cms-koa-core#2]
https://github.com/TaleLin/lin-cms-koa-core/blob/351f4a1d7e99b0773306561f6eeecc675932e8fd/lib/interface.ts#L36

User 里flask版是返回 super, 此版 为admin字段，这会让isSuper判断失效。

**Comment by PedroGao** [comment]
flask版目前已经修改为admin了，前端部分也进行了修改，即将和到master上。
