### ISSUE TITLE
如果 scheme 不等于 'Bearer' 怎么办？

### ISSUE THREAD

**Issue by zaxlct** [TaleLin/lin-cms-koa-core#29]
https://github.com/TaleLin/lin-cms-koa-core/blob/52591ea3a385f3bdf99822862c5ff1165dd824e3/lib/jwt.ts#L275

**Comment by vanoneang** [comment]
相当于令牌失效，前端自动刷新令牌

**Comment by zaxlct** [comment]
@vanoneang 但我看代码里没有 else ，没有抛出异常
